language: python
sudo: required
dist: trusty
python: 3.6
group: deprecated-2017Q2
cache:
  directories:
  - $HOME/.pip/wheels
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
{% for env, config in tox_environments|dictsort %}
    - ENV={{ env }}
{% endfor %}
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - mkdir -p ~/.pip
  - cp ci/pip.conf ~/.pip/pip.conf
  - pip install -U wheel setuptools tox cookiecutter bumpversion
script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - ci/test.sh $ENV
notifications:
  email:
    on_success: never
    on_failure: always
